version: '3.8'

services:
  webapi:
    container_name: conduit-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    container_name: conduit-db
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: conduit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

