// <auto-generated />
using Conduit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conduit.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Conduit.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Conduit.Entities.User", b =>
                {
                    b.OwnsOne("Conduit.Entities.Profile", "Profile", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("id");

                            b1.Property<string>("Bio")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("bio");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(10000)
                                .HasColumnType("TEXT")
                                .HasColumnName("image_url");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("username");

                            b1.HasKey("UserId")
                                .HasName("pk_profile");

                            b1.ToTable("profile", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_profile_users_id");
                        });

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
